---
abstract: 'Download kernels from http://kernel.ubuntu.com/~kernel-ppa/mainline/.'
author:
  - 'Kai-Heng Feng <khfeng@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Uptake
requires:
  App::Cmd::Setup: '0'
  Carp: '0'
  File::chdir: '0'
  List::Util: '0'
  Mojo::UserAgent: '0'
  autodie: '0'
  feature: '0'
  strict: '0'
  warnings: '0'
version: 0.1.3
